\set schema_name :DB_SCHEMA

BEGIN;

CREATE TABLE IF NOT EXISTS :schema_name.audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_provider_id INTEGER NOT NULL, -- no foreign key
    service_account_id INTEGER NOT NULL, -- no foreign key
    action_type VARCHAR(50) NOT NULL, -- CREATE, UPDATE, DELETE, ADD_USER, REMOVE_USER, etc.
    resource_type VARCHAR(50) NOT NULL, -- user, group, organisation, etc.
    resource_id INTEGER, -- ID of the affected resource
    new_values JSONB, -- New state (for creates/updates)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX idx_audit_logs_service_account ON :schema_name.audit_logs(service_account_id);
CREATE INDEX idx_audit_logs_action_type ON :schema_name.audit_logs(action_type);
CREATE INDEX idx_audit_logs_resource ON :schema_name.audit_logs(resource_type, resource_id);
CREATE INDEX idx_audit_logs_created_at ON :schema_name.audit_logs(created_at);

COMMIT;
