\set schema_name :DB_SCHEMA

CREATE SCHEMA :schema_name;

BEGIN;

-- Create the database tables

-- Organizations table
CREATE TABLE IF NOT EXISTS :schema_name.organisations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siren CHAR(9) NOT NULL UNIQUE CHECK (siren ~ '^[0-9]{9}$'),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Groups table
CREATE TABLE  IF NOT EXISTS :schema_name.groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orga_id INTEGER NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_orga FOREIGN KEY (orga_id) REFERENCES :schema_name.organisations (id) ON DELETE CASCADE
);

-- Parent-Child relationship table
CREATE TABLE IF NOT EXISTS :schema_name.parent_child_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_group_id INTEGER NOT NULL,
    child_group_id INTEGER NOT NULL,
    inherit_scopes BOOLEAN NOT NULL DEFAULT false,
    UNIQUE (parent_group_id, child_group_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_parent_child_parent FOREIGN KEY (parent_group_id) REFERENCES :schema_name.groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_parent_child_child FOREIGN KEY (child_group_id) REFERENCES :schema_name.groups (id) ON DELETE CASCADE
);

-- Users table
CREATE TABLE IF NOT EXISTS :schema_name.users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    sub_pro_connect VARCHAR(255),
    is_email_confirmed BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Roles table
CREATE TABLE IF NOT EXISTS :schema_name.roles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(255) NOT NULL UNIQUE,
    is_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Group users
CREATE TABLE IF NOT EXISTS :schema_name.group_user_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    role_id INTEGER NOT NULL,
    UNIQUE (group_id, user_id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT group_user_fk_relation_group FOREIGN KEY (group_id) REFERENCES :schema_name.groups (id) ON DELETE CASCADE,
    CONSTRAINT group_user_fk_relation_user FOREIGN KEY (user_id) REFERENCES :schema_name.users (id) ON DELETE CASCADE,
    CONSTRAINT group_user_fk_relation_role FOREIGN KEY (role_id) REFERENCES :schema_name.roles (id) ON DELETE CASCADE
);

-- Service Providers table
CREATE TABLE  IF NOT EXISTS :schema_name.service_providers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Scopes table
CREATE TABLE  IF NOT EXISTS :schema_name.group_service_provider_relations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_provider_id INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    UNIQUE (service_provider_id, group_id),
    scopes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scopes_group FOREIGN KEY (group_id) REFERENCES :schema_name.groups (id) ON DELETE CASCADE,
    CONSTRAINT fk_scopes_project FOREIGN KEY (service_provider_id) REFERENCES :schema_name.service_providers (id) ON DELETE CASCADE
);

-- Service Account table
CREATE TABLE  IF NOT EXISTS :schema_name.service_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_provider_id INTEGER NOT NULL,
    deactivated BOOLEAN NOT NULL DEFAULT false,
    name VARCHAR(255) NOT NULL,
    hashed_password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sa_sp_id FOREIGN KEY (service_provider_id) REFERENCES :schema_name.service_providers (id) ON DELETE CASCADE
);

INSERT INTO :schema_name.roles (id, role_name, is_admin) VALUES
(1, 'administrateur', true),
(2, 'agent', false),
(3, 'prestataire', false) ON CONFLICT (id) DO NOTHING;

COMMIT;
